# -*- coding: utf-8 -*-
"""Image Generation using GenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fHIxioKf4wgti_61XLW8L4HU3FP07lf
"""

#diffuse deals image data
!pip install diffusers --upgrade

!pip install transformers invisible_watermark safetensors accelerate

from diffusers import DiffusionPipeline
import torch

#load pretrained model
pipe=DiffusionPipeline.from_pretrained(
    #model
    'stabilityai/stable-diffusion-xl-base-1.0',
    #datatype
    torch_dtype=torch.float16,
    #safe tensors
    user_safetensors=True,#avoide error of float
    #variants
    variant='fp16'
)

pipe.to("cuda")#if ur system have GPU ,it uses else it use 'CPU'

#To generate images by giving prompt
prompt="A portrait of famous cricketer virat kohli in cricket uniform"
negative_prompt="Avoid icluding other people in the scene"
images=pipe(prompt=prompt,negative_prompt=negative_prompt).images[0]

import matplotlib.pyplot as plt
plt.imshow(images)
plt.axis("off")
plt.show()